/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  v5SideBar: [
    // 'v5/intro',
    'v5/guide',
    'v5/acct-mode',
    'v5/announcement',
    'v5/smp',
    'v5/demo',
    'v5/system-status',
    {
      type: 'category',
      label: 'Market',
      items: [
        {
          type: 'autogenerated',
          dirName: 'v5/market'
        }
      ]
    },
    {
      type: 'category',
      label: 'Trade',
      items: [
        {
          type: 'autogenerated',
          dirName: 'v5/order'
        }
      ]
    },

    {
      type: 'category',
      label: 'Account',
      items: [
        {
          type: 'autogenerated',
          dirName: 'v5/account'
        }
      ]
    },
    {
      type: 'category',
      label: 'Asset',
      items: [
        'v5/asset/delivery',
        'v5/asset/settlement',
        'v5/asset/exchange',
        'v5/asset/coin-info',
        'v5/asset/sub-uid-list',
        {
          type: 'category',
          label: 'Balances',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/asset/balance'
            }
          ]
        },
        {
          type: 'category',
          label: 'Transfer',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/asset/transfer'
            }
          ]
        },
        {
          type: 'category',
          label: 'Deposit',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/asset/deposit'
            }
          ]
        },
        {
          type: 'category',
          label: 'Withdraw',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/asset/withdraw'
            }
          ]
        },
        {
          type: 'category',
          label: 'Convert',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/asset/convert'
            }
          ]
        },
        {
          type: 'category',
          label: 'Fiat-Convert',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/asset/fiat-convert'
            }
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'User',
      items: [
        {
          type: 'autogenerated',
          dirName: 'v5/user'
        }
      ]
    },


    {
      type: 'category',
      label: 'Crypto Loan (New)',
      items: [
        'v5/new-crypto-loan/loan-coin',
        'v5/new-crypto-loan/collateral-coin',
        'v5/new-crypto-loan/reduce-max-collateral-amt',
        'v5/new-crypto-loan/adjust-collateral',
        'v5/new-crypto-loan/ltv-adjust-history',
        'v5/new-crypto-loan/crypto-loan-position',
        {
          type: 'category',
          label: 'Flexible Loan',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/new-crypto-loan/flexible'
            }
          ]
        },
        {
          type: 'category',
          label: 'Fixed Loan',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/new-crypto-loan/fixed'
            }
          ]
        }
      ]
    },

    {
      type: 'category',
      label: 'Institutional Loan',
      items: [
        {
          type: 'autogenerated',
          dirName: 'v5/otc'
        }
      ]
    },

    {
      type: 'category',
      label: 'Earn',
      items: [
        {
          type: 'autogenerated',
          dirName: 'v5/earn'
        }
      ]
    },

    {
      type: 'category',
      label: 'WebSocket Stream',
      items: [
        'v5/websocket/wss-authentication',
        {
          type: 'category',
          label: 'Public',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/websocket/public'
            }
          ]
        },
        {
          type: 'category',
          label: 'Private',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/websocket/private'
            }
          ]
        },
        {
          type: 'category',
          label: 'Trade',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/websocket/trade'
            }
          ]
        },
        {
          type: 'category',
          label: 'System',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/websocket/system'
            }
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Rate Limit',
      items: [
        'v5/rate-limit/rate-limit',
        'v5/rate-limit/rules-for-vips',
        {
          type: 'category',
          label: 'API Rate Limit Rules for PROs',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v5/rate-limit/rules-for-pros'
            }
          ]
        },
      ]
    },
    'v5/enum',
    'v5/error',
  ],
  apiExplorerSideBar: [
    {
      type: "category",
      label: "V5",
      link: {
        type: "generated-index",
        title: "V5 API",
        slug: "/api-explorer/v5/category/"
      },
      // @ts-ignore
      items: [
        require("./docs/api-explorer/v5/market/sidebar.js"),
        require("./docs/api-explorer/v5/trade/sidebar.js"),
        require("./docs/api-explorer/v5/position/sidebar.js"),
        require("./docs/api-explorer/v5/account/sidebar.js"),
        require("./docs/api-explorer/v5/asset/sidebar.js"),
        require("./docs/api-explorer/v5/user/sidebar.js"),
        require("./docs/api-explorer/v5/lt/sidebar.js"),
        require("./docs/api-explorer/v5/spot-margin-uta/sidebar.js"),
      ]
    }
  ],
  changelogSidebar: [
    "changelog/v5"
  ]
};

module.exports = sidebars;
